### ISSUE TITLE
iframeの属性について

### ISSUE THREAD

**Issue by curiburn** [utahta/WP-Social-Bookmarking-Light#18]
今のところHTML5のValidatorにひっかるだけで表示には問題ないのですが、出力における<iframe>の属性のallowtransparency, frameborder,scrollingをstyleの中でCSSとして書くよう次期アップデートで検討して欲しいです。

**Comment by utahta** [comment]
対応する時間が取れそうにないので、良ければぜひ PR お願いします！
いったん閉じます
