### ISSUE TITLE
chromeでアイコンが表示されない？？

### ISSUE THREAD

**Issue by yeguchi** [utahta/WP-Social-Bookmarking-Light#24]
バージョンアップしてからchromeでアイコンが表示されなくなりました。LINEとはてな、は表示されます。

**Comment by utahta** [comment]
報告ありがとうございます。
ちなみに何のアイコンが表示されないでしょうか？
使用中のWordPressのバージョンや、テーマなども教えていただけると調査が捗りますmm

**Comment by utahta** [comment]
閉じます
