### ISSUE TITLE
Pocket と表示される

### ISSUE THREAD

**Issue by utahta** [utahta/WP-Social-Bookmarking-Light#25]
http://poporon.poponet.jp/20150228/6855
確認する

**Comment by hinaloe** [comment]
(フォーラムで上がってたのでついでに https://ja.forums.wordpress.org/topic/158691)

@ see

https://github.com/Automattic/jetpack/blob/fb248e969f92f0e17f37de3b3d2b4b3fb7afefff/modules/likes.php#L1051-L1053

**Comment by utahta** [comment]
oh...なるほどです。ありがとうございます！
