### ISSUE TITLE
Undefined index: dntが出ます

### ISSUE THREAD

**Issue by Ikaring** [utahta/WP-Social-Bookmarking-Light#28]
NOTICE: wp-content/plugins/wp-social-bookmarking-light/modules/services.php:109 - Undefined index: dnt

Twitterのデフォルトオプションに'dnt'がないのが原因ではないでしょうか。

**Comment by utahta** [comment]
oh...その通りですね。。ありがとうございます。
修正しますm(_ _)m

**Comment by Ikaring** [comment]
サクッとプルリク送れるようになりたいところですけど、どうぞよろしくお願いします。

あと、以前プラグインページのサポートに別の問題を投稿してたのですが、見ていただけましたでしょうか。必要ならこちらにもissue書きます。
https://wordpress.org/support/topic/activating-this-plugin-change-mata-description?replies=1

**Comment by utahta** [comment]
すみません、プラグインページの投稿いま確認しました。
こちらはちょっと調査してみないと分からなそうですね。。。
issue はお手数でなければよろしくお願いしますm(_ _)m

**Comment by utahta** [comment]
#29 `Undefined index: dnt` は 1.8.2 で修正反映しました
