### ISSUE TITLE
Twitterボタンのマークアップ出力にエラー

### ISSUE THREAD

**Issue by Ikaring** [utahta/WP-Social-Bookmarking-Light#31]
お世話になります。
お客さまのサイトにおいて使用しております。おおむね問題ないのですが、たまにFBのいいねボタンとTwitterのボタンが表示されないとの報告をいただき、確認をしていた際に、開発者ツールで「開始タグの形式が正しくありません。属性は空白文字で区切る必要があります。」というエラーが表示されていました。

当該部分のソースをみると下記のようになっていましたが、これは仕様なのでしょうか？
<a href="https://twitter.com/share" class="twitter-share-button"{count}

**Comment by utahta** [comment]
報告ありがとうございます！
なるほど。 `{count}` となっている部分、怪しそうですね。
確認してみますmm
