### ISSUE TITLE
「LINEで送る」で空のメッセージが送信される

### ISSUE THREAD

**Issue by mkgranfairs** [utahta/WP-Social-Bookmarking-Light#36]
WP-Social-Bookmarking-Lightを利用させていただいております。
表題の通りですが、「LINEで送る」押下で空のメッセージが送信される現象が発生しています。
何か解決の手がかりがあれば助かります。
## ▼手順と現象

WPに設置した、「LINE」で送るボタンを押下し、LINEが立ち上がる。
↓
送信先を選択
↓
メッセージとして送信
↓
で送信するも、空のメッセージ（吹き出し）が送られる。
## ▼使用環境情報

WPバージョン：　4.3.6
テーマ：　オリジナル

よろしくお願いします。

**Comment by utahta** [comment]
ご報告ありがとうございますmm
調べてみます。

**Comment by utahta** [comment]
http://wptest.ninxit.com/
WPバージョン：4.3.6
wp-social-bookmarking-lightバージョン：1.8.6
テーマ：デフォルト

上記のテストページで試しましたが再現できませんでした。
テーマ or 他プラグイン等の何かが干渉しているのかもしれません。

**Comment by utahta** [comment]
閉じます
