### ISSUE TITLE
WordPress 3.0.4で表示されない。

### ISSUE THREAD

**Issue by masaks** [utahta/WP-Social-Bookmarking-Light#49]
WP Social Bookmarking Light 1.9.2 を使用しています。
WordPress 旧バージョンの為でしょうか。対処法などおわかりでしたらご教示ください。
また、競合する可能性のあるプラグインなどの情報をお持ちでしたらお知らせいただければ幸いです。

**Comment by utahta** [comment]
PHPのバージョンと表示しようとしたボタンの種類を教えてもらえると調べやすいです。
ただ、3.0.4 はかなり古いので動かない可能性もあります。（セキュリティアップデートもされていないと思うので、ご利用自体おすすめできません）
競合プラグインは詳しくないですが、たくさんあると思います。
https://ja.wordpress.org/plugins/ で `social` や `social share` など検索してみてください。

**Comment by masaks** [comment]
ご返信ありがとうございます。
使用しているPHPは PHP 5.2.17 (cgi)です。
ボタンは Twitter、Facebook_like（シェア付き）、LINE の３種類の予定です。
wordpressのVerのアドバイスもありがとうございます。
先方の問題でアップグレードを躊躇される事もありまして 今一度おすすめしてみたいと思います。
また、競合というのは 動かない原因になりそうな他のプラグインやテーマの情報があれば、という意味でございました。
言葉足らずですみませんでした。
引き続き何卒宜しくお願い申し上げます。

**Comment by utahta** [comment]
情報ありがとうございます。確認しました。
[こちらソースコード](https://github.com/utahta/WP-Social-Bookmarking-Light/blob/master/modules/content.php#L143:145) の `get_query_var` の第二引数（デフォルト値の設定）が 3.0.4 だと未実装のようで、空文字が返ってきているようです。

上記部分を以下のように書き換えて頂くと、表示されると思います。
```php
if (get_query_var('amp') !== '') {
    return false;
}
```
（PHP 5.2 も既にセキュリティアップデート終了していますので、なるべく 5.6 以上の利用をオススメします）

> 競合というのは 動かない原因になりそうな他のプラグインやテーマの情報

なるほど、勘違いしましたmm
特にコレといったものはありません。
テーマによって表示が崩れることがあるかもしれませんが、その場合はプラグイン設定からボタン周りのスタイルを調整して頂ければと思います。

**Comment by masaks** [comment]
いただいた方法で無事表示されました！
素早くご対応いただき本当に助かりました。
御礼申し上げます。ありがとうございました。
