### ISSUE TITLE
Ver1.8.0以降Twitterボタン（ツイートアイコン）が表示されない

### ISSUE THREAD

**Issue by tanabem** [utahta/WP-Social-Bookmarking-Light#51]
はじめまして。お世話になります。
#31 や #32 と関係あるかどうか不明ですが、バージョン1.8.0以降、「ツイート」ボタンが表示されないという現象が発生しています。最新版の2.0.1でも試しましたが状況は変わりません。そのため、1.7.10にダウングレードして使っている状況です。ちなみに、Facebookの「いいね！」ボタンは問題なく表示されています。
なお、現在こちらで使っているWordPressのバージョンは4.8.1（4.7.2や4.7.5でも状況は同じ）、PHPのバージョンは5.3です。
おそらく、1.8.0の改修（* Fixed: Twitter Button）による影響かと思われますが、ご確認いただけますと助かります。
よろしくお願いいたします。

**Comment by utahta** [comment]
oh…なるほど。
手元（v2.0.1, PHP5.3, WordPress4.7・4.8）では表示されているので、何か他の要因があるかもですね。

もし可能であれば、v1.8.0 以降をお使いのときに何か javascript のエラーが出ていないかご確認いただけると嬉しいです。
（例えば Google Chrome の Developer Tools の console などで確認できます）

**Comment by tanabem** [comment]
お返事ありがとうございます。
ご指示の通り、v1.8.0 以降(v2.0.1)にアップデートし、 Firefox - Firebug - console と Google Chrome - Developer Tools - console にて javascript等のエラーが出ていないことを確認しました。

また、調査する中で１つわかったことがあります。
こちらでは、以前より twitter と facebook_like を使用しており、「iframe」タグがないとうまくリンクアイコンが表示されないという問題があり、「iframe」タグを選択＆設定していました。そして、v1.7.10までは、設定 - FBタブ - Versionで 「iframe」 を選択＆設定すると、下記両方のタグに 「iframe」 が適用されていました。
```
<div class="wsbl_facebook_like"><iframe src="//www.facebook.com/...(以下省略)
<div class="wsbl_twitter"><iframe src="//platform.twitter.com/...(以下省略)
```
ところが、v1.8.0以降は、設定の仕様が変わったようで、設定 - FBタブ - Versionで 「iframe」 を選択＆設定しても、facebook_like にしか iframeタグが適用されないようになってしまいました。その結果、Twitterアイコンが表示されないという現象が発生しているものと思われます。

そもそも、なぜ「iframe」でないとダメなのか（「xfbml」や「HTML5」ではダメなのか）がわかりません。おそらく、当方のサイト固有の問題かと思われますが。

そこで質問ですが、応急措置として、裏技（ファイルのダイレクト修正等）でも構いませんので、wsbl_twitter タグ内に、iframe タグを埋め込む方法をご教示いただけないでしょうか？

お手数をお掛けしますが、よろしくお願いいたします。

**Comment by tanabem** [comment]
念のため、v1.8.0 以降でTwitterアイコンが表示されない場合の画像を添付します。
![twitter](https://user-images.githubusercontent.com/6640007/29132409-17e80d62-7d6b-11e7-811a-5d3aaf60df23.png)

**Comment by tanabem** [comment]
V2.0.1で下記ファイルのTwitter部分を書き換えて、うまくアイコンが表示されることを確認しました。
`./wp-content/plugins/wp-social-bookmarking-light/src/WpSocialBookmarkingLight/Service.php`

取り急ぎお知らせまで。

**Comment by utahta** [comment]
詳細情報ありがとうございました！
v2.0.2 で iframe を選択できるようにしてみましたので、お試しいただければと思います。
プラグイン設定の Twitter タブから変更できます。
（もちろん直接書き替えで問題なければ、それでも大丈夫です！）

ちなみに Twitter ボタンの横幅などを調整したい場合は、プラグイン設定の CSS タブから .wsbl_twitter をいじってみてくださいmm

**Comment by tanabem** [comment]
迅速なご対応をありがとうございました！感謝申し上げます。
v2.0.2へアップデート後、問題なくTwitterアイコンが表示されることを確認しました。
ボタンのサイズは従来どおり（FBよりやや小さい）なので、当面このままでも大丈夫だと思います。

本件クローズいただいて結構です。今後とも、どうぞよろしくお願いいたします。
