### ISSUE TITLE
[feature request] please add php and shortcode embed options

### ISSUE THREAD

**Issue by d-packs** [utahta/WP-Social-Bookmarking-Light#54]
Some complex themes could use an option to position the buttons in a special position specified by the theme developer. Please add this support. it shouldn't be hard.

**Comment by utahta** [comment]
`wp_social_bookmarking_light_output_e` function don't have enough feature?

**Comment by d-packs** [comment]
It's good enough, but the hasty developer will just check documentation, if there is no shortcode documented,  he will just move to another plugin.

**Comment by utahta** [comment]
I see. I'll work to documented and add shortcode like `wp_social_bookmarking_light_output_e`.
