### ISSUE TITLE
上下の位置調整および機能付加要望

### ISSUE THREAD

**Issue by yumesaki** [utahta/WP-Social-Bookmarking-Light#6]
上下の位置調整、パラメータをどう変更(例えば最大値49に)しても余白に変化が見られません。
ソースを確認した限りCSSの「margin」で調整しているのだと思うのですが、、、テーマとの相性(テーマで指定しているCSSの何処かの記述とのバッティング)ですかね？

それとオプションで上または下に「hr(ホリゾンタルライン)」が入る設定が出来ると便利だと思う人が私を含め結構居ると思います。　機能付加ご検討をよろしくお願いします。

**Comment by utahta** [comment]
Fix `Custom CSS`
