### ISSUE TITLE
[bug] Language dropdown missing options content

### ISSUE THREAD

**Issue by d-packs** [utahta/WP-Social-Bookmarking-Light#60]
The language dropdown is not populated correctly for the GooglePlus button.

![selection_041](https://user-images.githubusercontent.com/33980111/35913634-007aadec-0c09-11e8-9303-fa9aad017e75.png)

**Comment by utahta** [comment]
wtf, I'll fix it.

**Comment by utahta** [comment]
Fixed in v2.0.7!
Thank you for your report.
